---
title: "回归分析"
author: "黄赫堂 2020201415"
date: "2024-12-18"
---
# 回归分析
## 加载包
```{r}
library(readxl)
library(dplyr)
```

## 读取数据
```{r}
salary <- read_excel("data.xlsx")
summary(salary)
```

## 处理数据
```{r}
### 公司规模哑变量赋值

dummy_scale <- model.matrix(~ salary$公司规模 - 1, data=salary)
salary <- cbind(salary, dummy_scale)
salary <- subset(salary,select = -公司规模)
```


```{r}
### 已有工作经验哑变量赋

dummy_experience <- model.matrix(~ salary$已有工作经验 - 1, data=salary)
salary <- cbind(salary, dummy_experience)
salary <- subset(salary,select = -已有工作经验)
```

```{r}
### 学历哑变量赋值
dummy_degree <- model.matrix(~ salary$学历 - 1, data=salary)
salary <- cbind(salary, dummy_degree)
salary <- subset(salary,select = -学历)
```

```{r}
### 融资阶段哑变量赋值
dummy_phase <- model.matrix(~ salary$融资阶段 - 1, data=salary)
salary <- cbind(salary, dummy_phase)
salary <- subset(salary,select = -融资阶段)
```

```{r}
### 福利哑变量赋值
salary <- salary %>% 
  mutate(福利 = case_when(
      福利 == TRUE ~ 1,
      福利 == FALSE ~ 0,
      TRUE ~ 福利
    ))
salary$福利 <- as.integer(salary$福利)
```

```{r}
### 位置哑变量赋值
dummy_location <- model.matrix(~ salary$位置 - 1, data=salary)
salary <- cbind(salary, dummy_location)
salary <- subset(salary,select = -位置)
```

```{r}
### 公司行业哑变量赋值
dummy_industry <- model.matrix(~ salary$公司行业 - 1, data=salary)
salary <- cbind(salary, dummy_industry)
salary <- subset(salary,select = -公司行业)
```

```{r}
### 职业类别哑变量赋值
dummy_category <- model.matrix(~ salary$职业类别 - 1, data=salary)
salary <- cbind(salary, dummy_category)
salary <- subset(salary,select = -职业类别)
salary <- subset(salary,select = - 职位)
salary <- subset(salary,select = - 年薪)
```
## 保存处理后的数据

```{r}
# 保存处理后的数据
write_xlsx(salary, "data_variables.xlsx")
```
